# VC2008
win32-msvc2008_ricoh{

#	QMAKE_CFLAGS	-= -Zc:wchar_t-

	# RELEASE
	QMAKE_CFLAGS_RELEASE = -O1 -MT
	QMAKE_LFLAGS_RELEASE  += /NODEFAULTLIB:"MSVCRT" /NODEFAULTLIB:"LIBCPMT"

	# DEBUG
	QMAKE_CFLAGS_DEBUG  = -Zi -MTd
	QMAKE_LFLAGS_DEBUG  += /NODEFAULTLIB:"MSVCRTD" /NODEFAULTLIB:"LIBCMTD" /NODEFAULTLIB:"LIBCPMTD"

}
